version: "3"

services:
  postgres:
    container_name: strapiDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - strapi

  strapi:
    container_name: strapi
    build:
      context: ../backend
      dockerfile: "../docker/nashuro/Dockerfile"
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - strapi-config:/app/config
      - strapi-public:/app/public
    networks:
      - strapi
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: "./nginx/Dockerfile"
      args:
        SSL_CERTIFICATE: "${SSL_CERTIFICATE}"
        SSL_CERTIFICATE_KEY: "${SSL_CERTIFICATE_KEY}"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - strapi
    depends_on:
      - strapi

volumes:
  strapi-config:
  strapi-public:
  postgres-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
